sources:
  - name: ubs_wealth_insights
    enabled: false
    fetcher: fetch_ubs_insights
    article_limit: 5
    category: private_banking
    region: global

  - name: citi_global_insights
    enabled: false
    fetcher: fetch_citi_insights
    article_limit: 5
    category: private_banking
    region: global

  - name: jpm_market_insights
    enabled: false
    fetcher: fetch_jpm_insights
    article_limit: 5
    category: investment_strategy
    region: global

  - name: blackrock_insights
    enabled: false
    fetcher: fetch_blackrock_insights
    article_limit: 5
    category: asset_management
    region: global

  - name: pimco_insights
    enabled: false
    fetcher: fetch_pimco_insights
    article_limit: 5
    category: asset_management
    region: global

  - name: bis_banking
    enabled: false
    fetcher: fetch_bis_reports
    article_limit: 3
    category: regulation
    region: global

  - name: imf_weo
    enabled: false
    fetcher: fetch_imf_weo
    article_limit: 3
    category: macroeconomics
    region: global

  - name: mckinsey_wealth
    enabled: false
    fetcher: fetch_mckinsey_wealth
    article_limit: 3
    category: consulting
    region: global

  - name: imf_capital_markets_news
    enabled: false
    fetcher: fetch_imf_capital_markets
    article_limit: 10
    category: investment_banking
    region: global

  - name: imf_gfsr
    enabled: false
    fetcher: fetch_imf_gfsr
    article_limit: 5
    category: financial_stability
    region: global

  - name: bis_bulletins
    enabled: false
    fetcher: fetch_bis_bulletins
    article_limit: 5
    category: regulation_liquidity
    region: global

  - name: fed_economic_research
    enabled: false
    fetcher: fetch_fed_econ
    article_limit: 5
    category: monetary_policy
    region: us

  - name: ecb_financial_stability
    enabled: false
    fetcher: fetch_ecb_financial_stability
    article_limit: 5
    category: banking_risk
    region: europe

  - name: reuters_global_markets
    enabled: false
    fetcher: fetch_reuters_markets
    article_limit: 10
    category: market_trends
    region: global

  - name: bbc_business
    enabled: true
    fetcher: fetch_bbc_business
    article_limit: 10
    category: market_trends
    region: global

  - name: citi_design_system_all_components
    enabled: true
    fetcher: fetch_all_citi_components
    article_limit: 50
    category: internal_docs
    region: internal

  - name: internal_email_newsletters
    enabled: true
    fetcher: fetch_email_newsletters
    path: data/newsletters
    category: email
    article_limit: 10
